LICENSE, examples/src/Fresh.hs, examples/src/Main.hs, examples/src/Teletype.hs, freer.cabal, src/Control/Monad/Freer.hs, src/Control/Monad/Freer/Exception.hs, src/Control/Monad/Freer/Internal.hs, src/Control/Monad/Freer/NonDetEff.hs, src/Control/Monad/Freer/Reader.hs, src/Control/Monad/Freer/State.hs, src/Control/Monad/Freer/StateRW.hs, src/Control/Monad/Freer/Trace.hs, src/Data/Open/Union.hs, tests/Tests/NonDetEff.hs
Renamed `qApp` and `qComp` to `applyEffs` and `composeEffs`, respectively.
Fixed some expected behavior in the `Teletype.runPure` handler. Started using `effs` in place of `r` for readability in the effect modules..
=> Add some docs

README.md, bench/Core.hs, effects.cabal, examples/src/Teletype.hs, src/Control/Monad/Effect.hs, src/Control/Monad/Effect/Coroutine.hs, src/Control/Monad/Effect/Cut.hs, src/Control/Monad/Effect/Internal.hs, src/Control/Monad/Effect/NonDetEff.hs, src/Control/Monad/Effect/Reader.hs, src/Control/Monad/Effect/State.hs, src/Control/Monad/Effect/StateRW.hs, src/Control/Monad/Effect/Trace.hs, src/Control/Monad/Effect/Writer.hs, src/Data/FTCQueue.hs, src/Data/Open/Union.hs, src/Data/Union.hs, tests/Tests/Exception.hs
Renames the following function:
- `decomp` to `decompose`
- `Arrows` to `Queue`
- Moves `Data.Open.Union` to `Data.Union`.
=> Rename internal functions for readability

src/Control/Monad/Effect/Internal.hs
On `master`, use of `Control.Monad.forever` diverges. `forever` is defined as:
```haskell
forever a = let a' = a *> a' in a'
```
This definition of `forever` does not diverge:
```haskell
forever a = let a' = a >> a' in a'
```
It appears that `<*>` is a little too strict in its second argument. This PR resolves that by not forcing the evaluation of the second argument unless the first argument is in `Val`.
This should bring `Eff` into better semantic alignment with the `Applicative`/`Monad` relations:
> Furthermore, the Monad and Applicative operations should relate as follows:
> 
>     pure = return
>     (<*>) = ap
> 
> The above laws imply:
> 
>     fmap f xs  =  xs >>= return . f
>     (>>) = (*>)
=> Make <*> lazy in its second argument where possible.

src/Data/Union.hs
This PR defines `Foldable`, `Functor`, `Traversable`, `Eq`, `Show`, `Eq1`, & `Show1` instances for `Union`s whose types all satisfy the same constraints.
=> Union instances

src/Data/Union.hs
This PR redefines the instances added in #8 s.t. the set of constraints which need to be satisfied for each is more tractable, resulting in (much) better compile times.
This is most notable with anything using `Traversable`, which depends on `Functor` and `Foldable` as well as the usual constraints on the head and union of the tail of the type list, but even for the relatively simple case of `Foldable`, it’s a fairly dramatic improvement.
=> More tractable Union instances

src/Data/Union.hs
This PR:
- Fixes redundant constraint warnings in ghc 8.2.1. It does this by renaming `FindElem` to `:<`, removing the old `:<` class, and defining `inj` & `prj` as functions instead of methods. This was measured to ensure that it did not regress runtime performance.
- Cleans up `Apply0` & `Apply1` by taking the `Union` directly, instead of a proxy for the type list & the index.
- Cleans up all of the instances using the above.
- Exports `Apply0` & `Apply1` so that consumers can use them to improve compile times.
- Further cleans up the `Functor` & `Traversable` instances by removing the casting & coercion.
- Defines methods lifting binary functions into `Union`s.
- Cleans up the `Eq` & `Eq1` instances using the above.
- Adds an `apply1` variant whose function argument receives a `Union` …
=> Fix redundant constraints, improve instances, export Apply{0,1}

effects.cabal, src/Control/Monad/Effect/Fail.hs, src/Control/Monad/Effect/Failure.hs
This PR adds a failure effect, an interpreter producing `Either`, & a `MonadFail` instance for constructing failures.
=> Fail effect

src/Data/Union.hs, src/Data/Union/Templates.hs
This PR marks `apply` & friends as `INLINABLE`, ensuring that their definitions are available in the interface file but still deferring the choice of whether to inline to the call site. It also does the same with the methods of `Functor` &c.
Finally, it defines a bunch of the other methods for `Foldable` &c., s.t. specialized definitions with optimized implementations of `length` (for example) will still use the optimized implementation when in a `Union`.
=> Inline apply

src/Control/Monad/Effect.hs, src/Control/Monad/Effect/Internal.hs, src/Data/Union.hs
It's sometimes annoying to include the `TypeOperators` extension just to use effects, so let's export `Member` and `Members`.
=> Export Member and Members constraints

effects.cabal, src/Control/Monad/Effect/TH.hs
Ports https://github.com/IxpertaSolutions/freer-effects/pull/28/files and https://github.com/TaktInc/freer/pull/3 for makeEff.
This should make generating type signatures and declarations for GADTs easier.
=> Port makeFreer from TaktInc/freer for makeEff

effects.cabal, src/Control/Monad/Effect.hs, src/Control/Monad/Effect/Coroutine.hs, src/Control/Monad/Effect/Cut.hs, src/Control/Monad/Effect/Internal.hs, src/Control/Monad/Effect/NonDet.hs, src/Control/Monad/Effect/Reader.hs, src/Control/Monad/Effect/Run.hs, src/Control/Monad/Effect/StateRW.hs, src/Control/Monad/Effect/TH.hs, src/Control/Monad/Effect/Trace.hs, src/Control/Monad/Effect/Writer.hs, src/Data/Union.hs, tests/Tests/NonDet.hs
This PR provides a system for composite interpreters, using a `Run` typeclass which is able to completely eliminate effectful computations (or at least, in a couple of cases, interpret them into `IO`).
It further:
- provides an `interpret` helper inspired by [`freer-simple`](https://github.com/lexi-lambda/freer-simple)
- tweaks `Yield` to produce a value
- defines a `runCoro` eliminator for `Yield` which runs the resulting computation to completion with the assistance of a helper function which maps partial results to inputs
- exports a few handlers so we don’t have to import `Internal` so often
- defines `NonDet` into `Internal` so we can de-orphan the `Alternative` and `MonadPlus` instances
- resolves a longstanding issue preventing the use of `MemberU2`
- ~~defines a `LastMember` …
=> Composite interpreters

effects.cabal, src/Data/Union/Templates.hs
Rather than showing a KnownNat error, a user will see this:
```
<interactive>:42:10: error:
• 'Either String' is not a member of the type-level list
'[Maybe, Down]
• In the expression: (prj x) :: Maybe (Either String ())
In an equation for 'y': y = (prj x) :: Maybe (Either String ())
```
=> Add prettier type errors for ElemIndex failures.

changelog.md, effects.cabal, src/Control/Monad/Effect.hs, src/Control/Monad/Effect/Internal.hs
This PR adds an `interposeState` handler à la `freer-simple`’s [`interposeS`](https://hackage.haskell.org/package/freer-simple-1.1.0.0/docs/Control-Monad-Freer-Internal.html#v:interposeS).
=> Interpose state

README.md, bench/Core.hs, examples/src/Coroutine.hs, examples/src/Cut.hs, examples/src/NonDet.hs, examples/src/Teletype.hs, examples/src/Trace.hs, src/Control/Monad/Effect.hs, src/Control/Monad/Effect/Coroutine.hs, src/Control/Monad/Effect/Cut.hs, src/Control/Monad/Effect/Exception.hs, src/Control/Monad/Effect/Fresh.hs, src/Control/Monad/Effect/Internal.hs, src/Control/Monad/Effect/NonDet.hs, src/Control/Monad/Effect/Reader.hs, src/Control/Monad/Effect/Resumable.hs, src/Control/Monad/Effect/State.hs, src/Control/Monad/Effect/Trace.hs, src/Control/Monad/Effect/Writer.hs, src/Data/Union.hs, tests/Tests/Coroutine.hs, tests/Tests/Exception.hs, tests/Tests/NonDet.hs, tests/Tests/Reader.hs
`:<` is kind of opaque, and breaks `haskell-src-exts`. Thus, 🔥
Since this is a breaking change we’ll want to bump the version, but since we have some other breaking changes planned (#23, #35), we might want to wait to actually apply the bump.
=> 🔥 the membership operator

src/Control/Monad/Effect/Trace.hs
Tracing to stdout can lead to bugs in apps that depend on structured
data written to stdout. Tracing to stderr is the most morally correct
choice.
=> Make runPrintingTrace output to stderr.

src/Data/Union.hs
This PR gives an explicit role annotation for `Union`, fixing #52. Opened for comment since this does in fact break us, as (regrettably) expected.
=> Role annotation

src/Control/Monad/Effect.hs, src/Control/Monad/Effect/Coroutine.hs, src/Control/Monad/Effect/Exception.hs, src/Control/Monad/Effect/Fail.hs, src/Control/Monad/Effect/Fresh.hs, src/Control/Monad/Effect/Internal.hs, src/Control/Monad/Effect/Reader.hs, src/Control/Monad/Effect/Resumable.hs, src/Control/Monad/Effect/State.hs, src/Control/Monad/Effect/StateRW.hs, src/Control/Monad/Effect/Trace.hs, src/Control/Monad/Effect/Writer.hs
=> Stateless effect handlers

src/Control/Monad/Effect/Internal.hs
We thread `interpose` through the rest of the effects but then we're also applying it to the continuation again. Changes `interpose` to just apply it to `q`.
=> Apply to q instead of k

src/Control/Monad/Effect/Reader.hs
`local` was applying its effects to the continuation.
**master:**
```haskell
λ Effect.run (runReader (1 :: Int) (local (succ :: Int -> Int) ask) :: Eff '[] Int)
2
λ Effect.run (runReader (1 :: Int) (local (succ :: Int -> Int) (ask :: Eff '[Reader Int] Int) >> ask) :: Eff '[] Int)
2
```
**this PR:**
```haskell
λ Effect.run (runReader (1 :: Int) (local (succ :: Int -> Int) ask) :: Eff '[] Int)
2
λ Effect.run (runReader (1 :: Int) (local (succ :: Int -> Int) (ask :: Eff '[Reader Int] Int) >> ask) :: Eff '[] Int)
1
```
=> Apply local’s effects locally-only.

src/Control/Monad/Effect/Coroutine.hs, src/Control/Monad/Effect/Internal.hs, src/Data/Union.hs
This PR defines a `forAll` function, lifting typeclass methods into `Union`s much like the old `ApplyAll` class did. Unlike `ApplyAll`, it’s defined inductively on the member list. While we aren’t (currently) able to flatten the nested `case`s out into (effectively) an O(1) `switch`, using `forAll` to define `PureEffect` & `Effect` instances for `Union`s results in a fairly dramatic reduction in allocations, and a slight speedup.
Depends on #66.
=> Efficient effect handling

effects.cabal, src/Control/Monad/Effect/Exception.hs, src/Control/Monad/Effect/Resource.hs
The current formulation of `bracket` is broken in the presence of
asynchronous exceptions. If the action passed to `bracket` rethrows an
exception, and the exception is delivered asynchronously, there can
occur a race where the cleanup handler is invoked twice, which is
disastrous in terms of correctness.
The correct way to do this is to use `Control.Exception.bracket`, which
correctly masks asynchronous exceptions while executing the body of a
`bracket` call. We accomplish this by creating a new `Resource` effect
that uses `interpret` and a natural transformation to `IO` to invoke
the `bracket` function provided by `base`.
=> Implement a Resource effect and remove broken `bracket`.
